[package]
name = "acme-dns-rust"
version = "0.1.0"
authors = ["Ramon Wehrli <ramon.wehrli@edu.gbssg.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "postgres", "chrono", "migrate" ] }
tokio = { version = "0.2", features = ["full"] }
uuid = { version = "0.8", features = ["v4"] }
simplelog = "^0.7.6"
bcrypt = "0.8.1"
warp = "0.2.4"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
acme-lib = "0.8.1"
