[package]
name = "acme-dns-rust"
version = "0.1.0"
authors = ["conblem <ramonwehrli@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["acme-dns", "acme", "lets-encrypt", "dns", "async"]
categories = ["command-line-utilities"]
repository = "https://github.com/conblem/acme-dns-rust/"
description = "Acme DNS implementation written in Rust"

[dependencies]
lazy_static = "1.4"
prometheus = "0.10"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = { version = "0.2.4", features = ["futures-03"]}
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-tokio", "macros", "migrate"] }
tokio = { version = "0.2", features = ["dns", "tcp", "udp"] }
uuid = { version = "0.8", features = ["v4"] }
simplelog = "0.8"
bcrypt = "0.8"
warp = { version = "0.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
acme-lib = "0.8"
trust-dns-server = "0.19"
trust-dns-client = "0.19"
parking_lot = "0.11"
futures-util = "0.3"
rustls = "0.18"
tokio-rustls = "0.14"
toml = "0.5"
anyhow = "1.0"

[features]
default = ["postgres"]

postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]