version: '3.9'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /postgres/data
    volumes:
      - ./postgres:/data
    ports:
      - 5432:5432