name: Musl
on:
  push:
    paths:
      - 'cross/**'
    branches:
      - master

jobs:
  build:
    name: Musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Github Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/conblem/musl-openssl:latest
          file: cross/Musl
          context: cross/
