name: Musl
on:
  push:
    paths:
      - 'cross/**'
    branches:
      - master

jobs:
  build:
    name: Musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: conblem/acme-dns-rust/musl
          tag_with_ref: true
          tag_with_sha: true
          dockerfile: cross/Musl
          path: cross/
