name: Release
on:
  push:
    paths-ignore:
      - 'cross/**'
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/bin/semantic-release-rust
          key: ${{ runner.os }}-semantic-release-rust-${{ hashFiles('.github/workflows/release.yaml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/install@v0.1
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          crate: semantic-release-rust
          version: 1.0.0-alpha.6
      - uses: bahmutov/npm-install@v1
      - run: npm ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: npx semantic-release
