name: Rust
on: [push]

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker pull docker.pkg.github.com/conblem/acme-dns-rust/musl
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cross
      - run: cross build --target x86_64-unknown-linux-musl --release

