name: Rust
on:
  push:
    paths-ignore:
      - 'cross/**'
    branches:
      - master

jobs:
  build_and_test:
    name: Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin/cross
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker pull docker.pkg.github.com/conblem/acme-dns-rust/musl
      - name: Install cross
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install cross
      - run: cross build --target x86_64-unknown-linux-musl --release
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: conblem/acme-dns-rust/acme-dns-rust
          tag_with_ref: true
          tag_with_sha: true
